server:
  port: 9050
  servlet:
    context-path: /poli/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-23-21-25-48.compute-1.amazonaws.com:5432/d2evo4vgdfsuhf
    username: tkrssrofuoqudv
    password: ef053c4eab99510a2ce3c1b40e7945316380fc8f6117e9b91783c131c72edd80
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
